USE [master]
GO

/****** Object:  Database [TaskArchive]    Script Date: 17.04.2020 22:07:15 ******/
CREATE DATABASE [TaskArchive]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TaskArchive', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TaskArchive.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TaskArchive_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TaskArchive_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TaskArchive].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TaskArchive] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TaskArchive] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TaskArchive] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TaskArchive] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TaskArchive] SET ARITHABORT OFF 
GO

ALTER DATABASE [TaskArchive] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TaskArchive] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TaskArchive] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TaskArchive] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TaskArchive] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TaskArchive] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TaskArchive] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TaskArchive] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TaskArchive] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TaskArchive] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TaskArchive] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TaskArchive] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TaskArchive] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TaskArchive] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TaskArchive] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TaskArchive] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TaskArchive] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TaskArchive] SET RECOVERY FULL 
GO

ALTER DATABASE [TaskArchive] SET  MULTI_USER 
GO

ALTER DATABASE [TaskArchive] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TaskArchive] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TaskArchive] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TaskArchive] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TaskArchive] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TaskArchive] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TaskArchive] SET  READ_WRITE 
GO

