USE [master]
GO

/****** Object:  Database [TodoRun]    Script Date: 17.04.2020 22:05:30 ******/
CREATE DATABASE [TodoRun]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TodoRun', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TodoRun.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TodoRun_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TodoRun_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TodoRun].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TodoRun] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TodoRun] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TodoRun] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TodoRun] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TodoRun] SET ARITHABORT OFF 
GO

ALTER DATABASE [TodoRun] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TodoRun] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TodoRun] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TodoRun] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TodoRun] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TodoRun] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TodoRun] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TodoRun] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TodoRun] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TodoRun] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TodoRun] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TodoRun] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TodoRun] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TodoRun] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TodoRun] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TodoRun] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TodoRun] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TodoRun] SET RECOVERY FULL 
GO

ALTER DATABASE [TodoRun] SET  MULTI_USER 
GO

ALTER DATABASE [TodoRun] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TodoRun] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TodoRun] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TodoRun] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TodoRun] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TodoRun] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TodoRun] SET  READ_WRITE 
GO

